[package]
name = "cards_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
csv = "1.3.1"
lazy_static = "1.5.0"
rand = "0.9.0"
serde = { version = "1.0.218", features = ["derive"] }
